#!/usr/bin/env python3
"""PRESTO ML Pipeline for Synthetic SDLC Data.

Runs the full ML pipeline (feature engineering, model training, evaluation)
on synthetic data generated by the copula-based generator. Replicates the
same logic as Amit's analysis notebooks but is fully self-contained.

Usage:
    python run_pipeline.py [--domain DOMAIN] [--all] [--verbose]

Examples:
    python run_pipeline.py
    python run_pipeline.py --domain card-payment-processor --verbose
    python run_pipeline.py --all
"""
from __future__ import annotations

import argparse
import sys
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import Lasso, LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR / "output"

ALL_DOMAINS = ["abc-cloud-provider", "card-payment-processor", "xyz-sales-force"]

CSV_FILES = [
    "production_run_metrics.csv",
    "build_metrics.csv",
    "code_metrics.csv",
    "test_metrics.csv",
    "performance_testing_metrics.csv",
    "chaos_testing_metrics.csv",
    "requirements_metrics.csv",
    "uat_metrics.csv",
]

TARGET_COLUMN = "System Uptime (%)"

# Metrics used for rolling window features (same list as Amit's notebook,
# mapped to columns that actually exist in synthetic CSVs).
ROLLING_METRICS = [
    "Build Success Rate (%)",
    "System Uptime (%)",
    "Customer Satisfaction Score (1-10)",
]

# Metrics used for lag features.
LAG_METRICS = [
    "Build Success Rate (%)",
    "System Uptime (%)",
    "Customer Satisfaction Score (1-10)",
    "Throughput (RPS)",
]

ROLLING_WINDOWS = [3, 5, 7, 10]
LAG_STEPS = [1, 2, 3, 5]

# Columns to exclude from the feature matrix regardless.
EXCLUDE_COLUMNS = {"Date", "Release Number", TARGET_COLUMN}


# ---------------------------------------------------------------------------
# Data classes for structured results
# ---------------------------------------------------------------------------
@dataclass
class ModelResult:
    """Holds evaluation metrics for a single model."""

    name: str
    cv_r2_mean: float
    cv_r2_std: float
    holdout_r2: float
    holdout_mae: float
    holdout_rmse: float


@dataclass
class PipelineResults:
    """Aggregated results from a single domain pipeline run."""

    domain: str
    n_samples: int
    n_features: int
    target_mean: float
    target_std: float
    model_results: List[ModelResult] = field(default_factory=list)
    feature_importances: Optional[pd.DataFrame] = None
    leakage_features: List[str] = field(default_factory=list)
    results_with_leakage: List[ModelResult] = field(default_factory=list)
    results_without_leakage: List[ModelResult] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Step 1: Load and merge CSVs
# ---------------------------------------------------------------------------
def load_and_merge(domain_dir: Path, verbose: bool = False) -> pd.DataFrame:
    """Load all 8 CSV files and merge on Date (outer join)."""
    dfs: Dict[str, pd.DataFrame] = {}
    for csv_name in CSV_FILES:
        csv_path = domain_dir / csv_name
        if not csv_path.exists():
            print(f"  WARNING: {csv_name} not found, skipping.")
            continue
        df = pd.read_csv(csv_path)
        if "Date" in df.columns:
            df["Date"] = pd.to_datetime(df["Date"])
        phase_key = csv_name.replace(".csv", "")
        dfs[phase_key] = df

    if not dfs:
        raise FileNotFoundError(f"No CSV files found in {domain_dir}")

    # Merge using production_run_metrics as the base, outer joining the rest.
    phase_names = list(dfs.keys())
    merged = dfs[phase_names[0]].copy()

    for phase_name in phase_names[1:]:
        right = dfs[phase_name]
        # Identify overlapping columns (besides Date and Release Number).
        merge_cols = ["Date"]
        if "Release Number" in merged.columns and "Release Number" in right.columns:
            merge_cols.append("Release Number")

        merged = merged.merge(
            right,
            on=merge_cols,
            how="outer",
            suffixes=("", f"_{phase_name}"),
        )

    # Sort by date.
    if "Date" in merged.columns:
        merged = merged.sort_values("Date").reset_index(drop=True)

    if verbose:
        print(f"  Merged dataset: {merged.shape[0]} rows x {merged.shape[1]} columns")

    return merged


# ---------------------------------------------------------------------------
# Step 2: Feature Engineering
# ---------------------------------------------------------------------------
def _available(columns: pd.Index, metric_list: List[str]) -> List[str]:
    """Return metrics from *metric_list* that exist in *columns*."""
    return [m for m in metric_list if m in columns]


def add_rolling_features(df: pd.DataFrame, verbose: bool = False) -> pd.DataFrame:
    """Add rolling-window aggregations for key metrics.

    Rolling stats are computed on the series shifted by 1 period first, so a
    row's rolling_* features summarize only strictly-prior releases. Without
    this shift, pandas' default trailing window includes the current row,
    which for ROLLING_METRICS == TARGET_COLUMN means the feature literally
    contains the value being predicted at that row (same-row leakage, not
    temporal autocorrelation).
    """
    df_out = df.copy()
    metrics = _available(df_out.columns, ROLLING_METRICS)
    added = 0
    for metric in metrics:
        shifted = df_out[metric].shift(1)
        for window in ROLLING_WINDOWS:
            roll = shifted.rolling(window=window, min_periods=1)
            df_out[f"{metric}_rolling_mean_{window}"] = roll.mean()
            df_out[f"{metric}_rolling_std_{window}"] = roll.std()
            df_out[f"{metric}_rolling_min_{window}"] = roll.min()
            df_out[f"{metric}_rolling_max_{window}"] = roll.max()
            # Coefficient of variation (std / mean), guarded against zero.
            rolling_mean = df_out[f"{metric}_rolling_mean_{window}"]
            rolling_std = df_out[f"{metric}_rolling_std_{window}"]
            df_out[f"{metric}_rolling_cv_{window}"] = rolling_std / (
                rolling_mean + 1e-8
            )
            added += 5
    if verbose:
        print(f"  Rolling features added: {added} columns")
    return df_out


def add_lag_features(df: pd.DataFrame, verbose: bool = False) -> pd.DataFrame:
    """Add lag, pct_change, and diff features for key metrics."""
    df_out = df.copy()
    metrics = _available(df_out.columns, LAG_METRICS)
    added = 0
    for metric in metrics:
        for lag in LAG_STEPS:
            df_out[f"{metric}_lag_{lag}"] = df_out[metric].shift(lag)
            df_out[f"{metric}_pct_change_{lag}"] = df_out[metric].pct_change(
                periods=lag
            )
            df_out[f"{metric}_diff_{lag}"] = df_out[metric] - df_out[metric].shift(lag)
            added += 3
    if verbose:
        print(f"  Lag features added: {added} columns")
    return df_out


def add_cross_phase_features(
    df: pd.DataFrame, verbose: bool = False
) -> pd.DataFrame:
    """Add derived cross-phase composite features."""
    df_out = df.copy()
    added = 0

    # quality_score = Unit Test Coverage * Integration Test Coverage / 100
    utc_col = "Unit Test Coverage (%)"
    itc_col = "Integration Test Coverage (%)"
    if utc_col in df_out.columns and itc_col in df_out.columns:
        df_out["quality_score"] = (df_out[utc_col] * df_out[itc_col]) / 100
        added += 1

    # stability_score = Build Success Rate * Test Pass Rate / 100
    bsr_col = "Build Success Rate (%)"
    tpr_col = "Test Pass Rate (%)"
    if bsr_col in df_out.columns and tpr_col in df_out.columns:
        df_out["stability_score"] = (df_out[bsr_col] * df_out[tpr_col]) / 100
        added += 1

    if verbose:
        print(f"  Cross-phase features added: {added} columns")
    return df_out


def engineer_features(df: pd.DataFrame, verbose: bool = False) -> pd.DataFrame:
    """Run the full feature engineering pipeline and return the result."""
    if verbose:
        print("  Feature engineering ...")

    df_out = add_rolling_features(df, verbose=verbose)
    df_out = add_lag_features(df_out, verbose=verbose)
    df_out = add_cross_phase_features(df_out, verbose=verbose)

    # Handle NaN: forward-fill, backward-fill, then column mean.
    df_out = df_out.ffill().bfill()
    for col in df_out.select_dtypes(include=[np.number]).columns:
        if df_out[col].isna().any():
            df_out[col] = df_out[col].fillna(df_out[col].mean())

    # Replace infinities.
    df_out = df_out.replace([np.inf, -np.inf], np.nan)
    for col in df_out.select_dtypes(include=[np.number]).columns:
        if df_out[col].isna().any():
            df_out[col] = df_out[col].fillna(df_out[col].mean())

    return df_out


# ---------------------------------------------------------------------------
# Step 3: Prepare feature matrix and identify target leakage
# ---------------------------------------------------------------------------
def prepare_features(
    df: pd.DataFrame, exclude_leakage: bool = False, verbose: bool = False
) -> Tuple[pd.DataFrame, pd.Series, List[str]]:
    """Select numeric features, identify leakage columns, return X, y, leakage list."""
    if TARGET_COLUMN not in df.columns:
        raise ValueError(f"Target column '{TARGET_COLUMN}' not found in dataset")

    y = df[TARGET_COLUMN].copy()

    # Select only numeric columns.
    numeric_df = df.select_dtypes(include=[np.number])

    # Drop excluded columns.
    feature_cols = [c for c in numeric_df.columns if c not in EXCLUDE_COLUMNS]

    # Identify target-leakage features: any rolling/lag/pct_change/diff
    # derived from the target column itself.
    target_prefix = TARGET_COLUMN
    leakage_cols = [
        c
        for c in feature_cols
        if c.startswith(target_prefix + "_rolling_")
        or c.startswith(target_prefix + "_lag_")
        or c.startswith(target_prefix + "_pct_change_")
        or c.startswith(target_prefix + "_diff_")
    ]

    if verbose and leakage_cols:
        print(f"  Target-derived (leakage) features: {len(leakage_cols)}")

    if exclude_leakage:
        feature_cols = [c for c in feature_cols if c not in leakage_cols]

    X = df[feature_cols].copy()
    return X, y, leakage_cols


# ---------------------------------------------------------------------------
# Step 4 & 5: Train and evaluate models
# ---------------------------------------------------------------------------
def build_models() -> Dict[str, object]:
    """Return a dictionary of fresh (untrained) model instances."""
    return {
        "Linear Regression": LinearRegression(),
        "Ridge Regression": Ridge(alpha=1.0),
        "Lasso Regression": Lasso(alpha=1.0),
        "Random Forest": RandomForestRegressor(
            n_estimators=100,
            max_depth=10,
            min_samples_split=5,
            min_samples_leaf=2,
            random_state=42,
        ),
        "Gradient Boosting": GradientBoostingRegressor(
            n_estimators=100,
            max_depth=6,
            learning_rate=0.1,
            min_samples_split=5,
            min_samples_leaf=2,
            random_state=42,
        ),
    }


def train_and_evaluate(
    X: pd.DataFrame,
    y: pd.Series,
    verbose: bool = False,
) -> Tuple[List[ModelResult], Optional[pd.DataFrame]]:
    """Run 80/20 temporal split, StandardScaler, 5-fold TimeSeriesSplit CV.

    Returns a list of ModelResult and a DataFrame of RF feature importances.
    """
    # 80/20 temporal split (data is already sorted by Date).
    split_idx = int(len(X) * 0.8)
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

    # StandardScaler: fit on train, transform both.
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    tscv = TimeSeriesSplit(n_splits=5)
    models = build_models()
    results: List[ModelResult] = []
    rf_importances: Optional[pd.DataFrame] = None

    for name, model in models.items():
        # 5-fold TimeSeriesSplit cross-validation.
        cv_scores: List[float] = []
        for train_idx, val_idx in tscv.split(X_train):
            fold_scaler = StandardScaler()
            X_fold_train = fold_scaler.fit_transform(X_train.iloc[train_idx])
            X_fold_val = fold_scaler.transform(X_train.iloc[val_idx])
            y_fold_train = y_train.iloc[train_idx]
            y_fold_val = y_train.iloc[val_idx]

            # Clone-like approach: get a fresh model per fold for fairness.
            from sklearn.base import clone

            fold_model = clone(model)
            fold_model.fit(X_fold_train, y_fold_train)
            fold_pred = fold_model.predict(X_fold_val)
            cv_scores.append(r2_score(y_fold_val, fold_pred))

        cv_mean = float(np.mean(cv_scores))
        cv_std = float(np.std(cv_scores))

        # Re-train on full training set for holdout evaluation.
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)

        holdout_r2 = float(r2_score(y_test, y_pred))
        holdout_mae = float(mean_absolute_error(y_test, y_pred))
        holdout_rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))

        mr = ModelResult(
            name=name,
            cv_r2_mean=cv_mean,
            cv_r2_std=cv_std,
            holdout_r2=holdout_r2,
            holdout_mae=holdout_mae,
            holdout_rmse=holdout_rmse,
        )
        results.append(mr)

        if verbose:
            print(
                f"    {name:<25s}  CV R2={cv_mean:.4f}+/-{cv_std:.4f}  "
                f"Holdout R2={holdout_r2:.4f}  MAE={holdout_mae:.4f}  "
                f"RMSE={holdout_rmse:.4f}"
            )

        # Capture Random Forest feature importances.
        if name == "Random Forest":
            rf_importances = (
                pd.DataFrame(
                    {"feature": X.columns, "importance": model.feature_importances_}
                )
                .sort_values("importance", ascending=False)
                .head(20)
                .reset_index(drop=True)
            )

    return results, rf_importances


# ---------------------------------------------------------------------------
# Step 6: Report generation
# ---------------------------------------------------------------------------
def generate_report(pr: PipelineResults) -> str:
    """Build a Markdown report string."""
    lines: List[str] = []

    lines.append(f"# ML Pipeline Results: {pr.domain}")
    lines.append("")
    lines.append("## Dataset Characteristics")
    lines.append("")
    lines.append(f"| Property | Value |")
    lines.append(f"|----------|-------|")
    lines.append(f"| Samples | {pr.n_samples} |")
    lines.append(f"| Features (with leakage) | {pr.n_features} |")
    lines.append(f"| Target column | {TARGET_COLUMN} |")
    lines.append(f"| Target mean | {pr.target_mean:.4f} |")
    lines.append(f"| Target std | {pr.target_std:.4f} |")
    lines.append("")

    # ------------------------------------------------------------------
    lines.append("## Target Leakage Analysis")
    lines.append("")
    if pr.leakage_features:
        lines.append(
            f"Found **{len(pr.leakage_features)}** target-derived features "
            f"(rolling/lag of '{TARGET_COLUMN}'):"
        )
        lines.append("")
        for feat in pr.leakage_features:
            lines.append(f"- `{feat}`")
        lines.append("")
    else:
        lines.append("No target-derived leakage features detected.")
        lines.append("")

    # ------------------------------------------------------------------
    def _results_table(model_list: List[ModelResult], heading: str) -> None:
        lines.append(f"## {heading}")
        lines.append("")
        lines.append(
            "| Model | CV R2 (mean +/- std) | Holdout R2 | Holdout MAE | Holdout RMSE |"
        )
        lines.append(
            "|-------|----------------------|------------|-------------|--------------|"
        )
        for mr in sorted(model_list, key=lambda m: m.holdout_r2, reverse=True):
            lines.append(
                f"| {mr.name} | {mr.cv_r2_mean:.4f} +/- {mr.cv_r2_std:.4f} "
                f"| {mr.holdout_r2:.4f} | {mr.holdout_mae:.4f} | {mr.holdout_rmse:.4f} |"
            )
        lines.append("")

    if pr.results_with_leakage:
        _results_table(pr.results_with_leakage, "Model Performance (WITH target-derived features)")

    if pr.results_without_leakage:
        _results_table(
            pr.results_without_leakage,
            "Model Performance (WITHOUT target-derived features)",
        )

    # ------------------------------------------------------------------
    if pr.feature_importances is not None and not pr.feature_importances.empty:
        lines.append("## Top 20 Feature Importances (Random Forest)")
        lines.append("")
        lines.append("| Rank | Feature | Importance |")
        lines.append("|------|---------|------------|")
        for rank, (_, row) in enumerate(pr.feature_importances.iterrows(), start=1):
            lines.append(f"| {rank} | {row['feature']} | {row['importance']:.6f} |")
        lines.append("")

    # ------------------------------------------------------------------
    lines.append("## Notes")
    lines.append("")
    lines.append(
        "- This data was generated by the copula-based synthetic SDLC generator, "
        "not hand-crafted."
    )
    lines.append("- 80/20 temporal split (sorted by Date, no shuffling).")
    lines.append("- StandardScaler fit on training set only.")
    lines.append("- 5-fold TimeSeriesSplit cross-validation.")
    lines.append(
        "- Models: Linear Regression, Ridge, Lasso, Random Forest, Gradient Boosting."
    )
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Pipeline orchestrator for a single domain
# ---------------------------------------------------------------------------
def run_domain_pipeline(domain: str, verbose: bool = False) -> PipelineResults:
    """Execute the full pipeline for one domain and return results."""
    domain_dir = OUTPUT_DIR / domain
    if not domain_dir.exists():
        raise FileNotFoundError(f"Domain directory not found: {domain_dir}")

    print(f"\n{'=' * 70}")
    print(f"  Domain: {domain}")
    print(f"{'=' * 70}")

    # Step 1: Load and merge.
    print("\n[Step 1] Loading and merging CSVs ...")
    df = load_and_merge(domain_dir, verbose=verbose)

    # Step 2: Feature engineering.
    print("[Step 2] Feature engineering ...")
    df_eng = engineer_features(df, verbose=verbose)

    # Step 3: Prepare features (with leakage).
    print("[Step 3] Preparing feature matrix and checking for target leakage ...")
    X_with, y, leakage_cols = prepare_features(
        df_eng, exclude_leakage=False, verbose=verbose
    )
    print(f"  Total features (with leakage): {X_with.shape[1]}")

    # Prepare features (without leakage).
    X_without, _, _ = prepare_features(
        df_eng, exclude_leakage=True, verbose=verbose
    )
    print(f"  Total features (without leakage): {X_without.shape[1]}")

    if leakage_cols:
        print(f"  Target-derived leakage features ({len(leakage_cols)}):")
        for feat in leakage_cols:
            print(f"    - {feat}")

    # Step 4 & 5: Train and evaluate.
    print("\n[Step 4/5] Training and evaluating models ...")

    print("\n  --- WITH target-derived features ---")
    results_with, fi_with = train_and_evaluate(X_with, y, verbose=verbose)

    print("\n  --- WITHOUT target-derived features ---")
    results_without, fi_without = train_and_evaluate(X_without, y, verbose=verbose)

    # Build results object.
    pr = PipelineResults(
        domain=domain,
        n_samples=len(df_eng),
        n_features=X_with.shape[1],
        target_mean=float(y.mean()),
        target_std=float(y.std()),
        leakage_features=leakage_cols,
        results_with_leakage=results_with,
        results_without_leakage=results_without,
        feature_importances=fi_without,  # Use clean (no-leakage) RF importances.
    )

    # Step 6: Report.
    print("\n[Step 6] Generating results report ...")
    report = generate_report(pr)
    report_path = domain_dir / "ml_results.md"
    report_path.write_text(report, encoding="utf-8")
    print(f"  Report saved to: {report_path}")

    # Print summary table.
    print("\n  === SUMMARY (without leakage) ===")
    print(
        f"  {'Model':<25s}  {'CV R2':>10s}  {'Holdout R2':>10s}  "
        f"{'MAE':>10s}  {'RMSE':>10s}"
    )
    print("  " + "-" * 70)
    for mr in sorted(results_without, key=lambda m: m.holdout_r2, reverse=True):
        print(
            f"  {mr.name:<25s}  {mr.cv_r2_mean:>10.4f}  {mr.holdout_r2:>10.4f}  "
            f"{mr.holdout_mae:>10.4f}  {mr.holdout_rmse:>10.4f}"
        )

    return pr


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run ML pipeline on synthetic SDLC data."
    )
    parser.add_argument(
        "--domain",
        type=str,
        default="abc-cloud-provider",
        help="Domain to process (default: abc-cloud-provider).",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        dest="run_all",
        help="Run for all 3 domains.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print extra detail during execution.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    domains = ALL_DOMAINS if args.run_all else [args.domain]

    all_results: List[PipelineResults] = []
    for domain in domains:
        try:
            pr = run_domain_pipeline(domain, verbose=args.verbose)
            all_results.append(pr)
        except Exception as exc:
            print(f"\nERROR processing {domain}: {exc}")
            if args.verbose:
                import traceback

                traceback.print_exc()

    if len(all_results) > 1:
        print(f"\n{'=' * 70}")
        print("  CROSS-DOMAIN COMPARISON (without leakage, best model per domain)")
        print(f"{'=' * 70}")
        for pr in all_results:
            best = max(pr.results_without_leakage, key=lambda m: m.holdout_r2)
            print(
                f"  {pr.domain:<30s}  Best: {best.name:<25s}  "
                f"R2={best.holdout_r2:.4f}  RMSE={best.holdout_rmse:.4f}"
            )

    print("\nDone.")


if __name__ == "__main__":
    main()
